openapi: 3.0.0 
info:
  title: H+ Sport API
  version: 1.0.0
tags: 
  - name: Article 
    description: Articles tags for H+ Sport Blog.


paths: 
  /product:
    get:
      tags:
        - Article
      responses:
        200: 
          description: This is a list of the products in the catalog of H+ Sport
          content: 
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      example: 400
                    name:
                      type: string
                      example: lemon Water

  
  /blog/articles:
    get:
      responses:
        200:
          description: this is a list of blog articles for the H+ Sport company.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties: 
                    createdDate: 
                      type: string
                      format: date
                    tagline:
                      type: string
                    content:
                      type: string
                    category:
                      type: string
                    tags:
                      type: array
                      items: 
                        type: string
                
