openapi: 3.0.0 
info:
  title: H+ Sport API
  version: 1.0.0
tags: 
  - name: Article 
    description: Articles tags for H+ Sport Blog.


paths: 
  /product/{productId}:
    get:
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: integer
            example: 12
        - in: header
          name: customer-security-header
          required: false
          schema:
            type: integer
            example: 12344-1324234-343242
      responses:
        200: 
          description: This is a list of the products in the catalog of H+ Sport
          content: 
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      example: 400
                    name:
                      type: string
                      example: lemon Water
  /product:
    get:
      parameters:
        - in: query
          name: pageNumber
          description: Page number to return 
          required: false
          schema: 
            type: integer
            example: 1
        - in: query
          name: pageSize
          description: Number of results in the page
          required: false
          schema: 
            type: integer
            example: 10
            maximum: 100
      responses:
        200: 
          description: This is a list of the products in the catalog of H+ Sport
          content: 
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      example: 400
                    name:
                      type: string
                      example: lemon Water

  
  /blog/articles:
    get:
      tags:
        - Article
      responses:
        200:
          description: this is a list of blog articles for the H+ Sport company.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties: 
                    createdDate: 
                      type: string
                      format: date
                    tagline:
                      type: string
                    content:
                      type: string
                    category:
                      type: string
                    tags:
                      type: array
                      items: 
                        type: string
                
