openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SAIDUPSKILLS_1/customer/1.0.0
info:
  description: This is an API for H+ Sports Customers
  version: "1.0.0"
  title: customers API
  contact:
    email: you@hplussport.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: customer
    description: customer related calls


paths:
  /customer:
    get:
      tags:
        - customer
      summary: searches inventory
      operationId: searchCustomer
      description: |
        By passing in the appropriate options, you can search for
        available customers in the system

      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        '400':
          description: bad input parameter
    
components:
  schemas:
    Customer:
      type: object
      required:
        - name
        - customerNumber
        
      properties:
        id:
          type: string
          example: d290f1ee
        name:
          type: string
          example: John Doe
        phone:
          type: string
          example: '125-234-9834'